### ISSUE TITLE
Numeric comparison when check-digit is 'X'

### ISSUE THREAD

**Issue by jesusbagpuss** [eprints/orcid_support#4]
In `EPrints::MetaField::Orcid::validate_orcid`, ([Line 77](https://github.com/eprints/orcid_support/blob/master/lib/plugins/EPrints/MetaField/Orcid.pm#L77))
`if( $res != $digits[15] )`
is not correct when the checkdigit is 'X'.

Possibly solution (although it feels inelegant):
`if( ($res eq 'X' && $digits[15] ne 'X') || ($res != $digits[15]) )`

_I'm not sure if `$res eq $digits[15]` works when both are numeric?_

**Comment by jesusbagpuss** [comment]
Looking at similar functionality in a module from CPAN, they do an `uc( $value) eq $check`.
http://cpansearch.perl.org/src/MAMAWE/Algorithm-CheckDigits-v1.3.2/lib/Algorithm/CheckDigits/M11_001.pm

Could do the same here.

**Comment by leg20-unikent** [comment]
Thanks for this solution, ran into the problem with validating ORCiDS with an "X" .

In the end I had to use the line:
`if( ($res eq 'X' && $digits[15] ne 'X') || ($res =~ /\d/ && $res != $digits[15]) )`
.. to avoid Perl complaining that the value is not numeric.

**Comment by jesusbagpuss** [comment]
Thanks for the update.
I've submitted a pull-request - hopefully we'll see this in the next release!
