### ISSUE TITLE
Add the ORCID to all publications of the same creator in a batch

### ISSUE THREAD

**Issue by zuphilip** [eprints/orcid_support#8]
We started to work with the plugin "ORCID Support" and can for any new publication enter the ORCIDs of the creators. However, this will leave untouched all the old data where e.g. the same creator is entered without an ORCID. Thus, we have now two suggestions for autocompletion of creators field:

![orcid-autocompletion](https://user-images.githubusercontent.com/5199995/37333152-dd5b262e-26a8-11e8-8bfc-73e484672637.png)

Is there any way to batch add the ORCID to all publications of the same author?

**Comment by zuphilip** [comment]
Maybe this triggered script from the ORCID support advance plugin goes in that direction https://github.com/eprints/orcid_support_advance/blob/master/lib/plugins/EPrints/Plugin/Event/UpdateCreatorOrcid.pm

**Comment by dennmuel** [comment]
I think this one can be closed now. Any auto-fill related issues should be kept to the orcid support advance repo, I guess.
